### ISSUE TITLE
Configure Travis CI

### ISSUE THREAD

**Issue by necojackarc** [necojackarc/breadcrumbs_on_rails-json_ld#4]

**Comment by yasaichi** [comment]
This `.travis.yml` perhaps works well:

```yaml
language: ruby
sudo: false
rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0
gemfile:
  - gemfiles/rails40x.gemfile
  - gemfiles/rails41x.gemfile
  - gemfiles/rails42x.gemfile
  - gemfiles/rails50x.gemfile
  - gemfiles/rails51x.gemfile
matrix:
  exclude:
    - rvm: 2.4.3
      gemfile: gemfiles/rails40x.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/rails41x.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails40x.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails41x.gemfile
branches:
  only:
    - master
before_install:
  - gem update --system --no-doc
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
```
